.PHONY: clean All

All:
	@echo "----------Building project:[ PEKSv2 - Debug ]----------"
	@"$(MAKE)" -f  "PEKSv2.mk"
clean:
	@echo "----------Cleaning project:[ PEKSv2 - Debug ]----------"
	@"$(MAKE)" -f  "PEKSv2.mk" clean
reset:
	rm -f textfiles/*kw textfiles/*sc keys/sk/* keys/pk/* server/*
