.PHONY: clean All

All:
	@echo "----------Building project:[ PEKSv2 - Debug ]----------"
	@"$(MAKE)" -f  "PEKSv2.mk"
clean:
	@echo "----------Cleaning project:[ PEKSv2 - Debug ]----------"
	@"$(MAKE)" -f  "PEKSv2.mk" clean
